image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://git.sr.ht/~tristan957/tristan.partin.io
  - https://git.sr.ht/~sircmpwn/openring
environment:
  ec2_box: ubuntu@partin.io
  # linode_instance: root@
secrets:
  - 7479e438-adaa-42f6-a774-def5194e2ae3
  - 823512b1-af97-446c-bff3-4f52ea414014
tasks:
  - openring: |
      cd openring
      go build
      mkdir -p ~/.local/bin
      cp openring ~/.local/bin
  - build: |
      cd tristan.partin.io
      openring \
        -s https://drewdevault.com/feed.xml \
        -s https://emersion.fr/blog/rss.xml \
        -s https://blog.golang.org/feed.atom \
        -s https://blog.rust-lang.org/feed.xml \
        < include/webring-in.html \
        > partial/webring-out.html
      hugo
  - deploy: |
      cd tristan.partin.io
      rsync --delete -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/personal-ec2.pem" public/ $ec2_box:/var/www/tristan.partin.io
      # rsync --delete -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ $ec2_box:/var/www/tristan.partin.io
