image: alpine/edge
packages:
  - go
  - hugo
  - rsync
sources:
  - https://github.com/Discord-Scout-Council/discord-scout-council.github.io.git
environment:
  kronos: deploy@kronos.devosmium.xyz
  # linode_instance: root@
secrets:
  - a88c3ffc-9bb0-451e-bf59-ef6198da6754
  - 0467a7c3-16d9-491c-9874-807bce4f2616
tasks:
  - build: |
      cd discord-scout-council.github.io
      hugo
  - deploy: |
      cd discord-scout-council.github.io
      rsync --delete -avz --exclude ".well-known" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ $kronos:/var/www/dscsite
      # rsync --delete -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public/ $ec2_box:/var/www/tristan.partin.io
