baseURL = "https://dsc.devosmium.xyz"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Discord Scout Council"
static = ["static"]
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

summary = "Discord Scout Council"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[pages]
  [pages.build]
    list = true
